### ISSUE TITLE
Additional options support

### ISSUE THREAD

**Issue by calebcartwright** [swellaby/azdo-shellcheck#15]
Should allow users to include the additional options supported by ShellCheck, but fall back to default ShellCheck behavior otherwise

* `-x` - follow sourced files
* `-f` output format (json, xml, etc.)
* `-d` dialect (sh/bash/ksh/etc.)
* `-e` exclude rules

**Edit 1** - Added `-e`

**Comment by calebcartwright** [comment]
@beverts312 - if you know of/want to see any other options please chime in

**Comment by beverts312** [comment]
Just one more:
`-e` rules to exclude 

Rules to exclude is a big one for me since I dont agree with all of shellchecks opinions
